version: "3"

services:
  database:
    image: postgres:latest
    ports:
      - "15432:5432"
    env_file:
      - .env
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge